name: fuelgo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  google_sign_in: ^6.1.5
  location: ^5.0.0
  latlong2: ^0.9.0
  http: ^1.2.1
  flutter_polyline_points: ^1.0.0
  flutter_tts: ^3.8.5
  clipboard: ^0.1.3
  shared_preferences: ^2.2.2
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.7.10
  image_picker: ^1.0.4
  intl: ^0.18.1
  fl_chart: ^0.66.0
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  carousel_slider: ^5.1.1
  camera: ^0.10.5
  path_provider: ^2.1.1
  mailer: ^6.0.1
  enough_mail: ^2.1.6
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides: 
  http: ^1.2.1
  

flutter:
  uses-material-design: true
  assets:
    - assets/fuelgo.png
    - assets/fuelgo1.png
    - assets/google_logo.png

flutter_launcher_icons:
     android: "launcher_icon"
     ios: true
     image_path: "assets/fuelgo2.png"
     min_sdk_android: 21
     adaptive_icon_background: "#ffffff" 
     adaptive_icon_foreground: "assets/fuelgo2.png"
